@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
together {
  class Professor {
    + listOfStudents : list
  }
  class Class {
      + Students : list
  }
}
Professor "1" o-- "1..*" Class
 @enduml
